// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDk5zjO8TZm2j0IG3OwhfNt0ldsiv7W0lM',
    appId: '1:524716560264:web:62f2df44a0d973ce96743d',
    messagingSenderId: '524716560264',
    projectId: 'anotherpaymentproject',
    authDomain: 'anotherpaymentproject.firebaseapp.com',
    storageBucket: 'anotherpaymentproject.firebasestorage.app',
    measurementId: 'G-S0E1R0JBRH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOgpYyzpS-FSwa0i9BtI7K2j0b_MyTrgw',
    appId: '1:524716560264:android:07221605c69ea70596743d',
    messagingSenderId: '524716560264',
    projectId: 'anotherpaymentproject',
    storageBucket: 'anotherpaymentproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBB0ABLWAuM7JcDS4dTEmnf39wHtzLwxsQ',
    appId: '1:524716560264:ios:393082544fe9c56596743d',
    messagingSenderId: '524716560264',
    projectId: 'anotherpaymentproject',
    storageBucket: 'anotherpaymentproject.firebasestorage.app',
    iosBundleId: 'com.example.payapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBB0ABLWAuM7JcDS4dTEmnf39wHtzLwxsQ',
    appId: '1:524716560264:ios:393082544fe9c56596743d',
    messagingSenderId: '524716560264',
    projectId: 'anotherpaymentproject',
    storageBucket: 'anotherpaymentproject.firebasestorage.app',
    iosBundleId: 'com.example.payapp',
  );

}